### ISSUE TITLE
Remove np.float, etc for compatibility with newest Numpy (> 1.24, I think)

### ISSUE THREAD

**Issue by agrossfield** [GrossfieldLab/loos#102]
## Describe the bug

LOOS still has a bunch of places where it refers to np.float (and perhaps other literal types). Numpy has deprecated this for a while, and I think in v1.24 it's going to switch from being a warning to an error. We should fix it before that.

## To Reproduce
Right now it just gives deprecation warnings. Basically, someone needs to grep through the pyloos codebase and find numpy.float and np.float and swap them, checking to make sure nothing breaks.

## Expected behavior
No warnings.

## LOOS version and platform
All loos versions. Will be a problem with people who have Numpy > 1.24 installed.

**Comment by agrossfield** [comment]
For what it's worth, this would make a great first issue for someone to work on, since solving it should be very straightforward.

**Comment by tromo** [comment]
fixed...grep turns up no more instances
