### ISSUE TITLE
improve error messages with file names when possible

### ISSUE THREAD

**Issue by lgsmith** [GrossfieldLab/loos#110]
## Is your feature request related to a problem? Please describe
I often have errors that arise as a script is handling thousands of trajectories inside pyloos, and because loos errors often dump core instead of triggering a traceback, and because the error msgs themselves often are about what's happening in deep parts of loos but are actually often 'bad input' errors, the issues with these scripts can be hard to address. 

@tromo and I have talked about this, and he suggested I raise a feature request issue about it. For example, if you have a bunch of coords that are all the same number, we can't write that to an XTC (with `XTCWriter`)---this isn't because the xtc writer is bad, but because the input data was. The error thrown, however, is about overflow upon coordinate compression, which is hard to understand.

## Describe the solution you'd like
The suggestion I had was to add to the extant error msg with some additional information making it clearer to n00bs what bad thing might be happening, and where. Broadly, I suggested that whenever an object that is associated with a file has an issue resulting in a thrown error, the error should contain the filename. So in the writer's case, something like:
`'the extant message' + 'the file: {filename} may be corrupt, or have bad coordinates. Suggest inspecting the file.'`

## Describe alternatives you've considered
Since this is a feature request and I was asked to write the issue, I haven't considered many. Often I wind up ripgrepping through the loos source to find the thrown error msg and see if I can figure out what's going wrong through contemplation, or I fill my scripts with print-statements to figure out which piece of input data is being worked on prior to the one that caused the code to bomb. 

## Additional context
This is the error message that sparked the conversation:
```
terminate called after throwing an instance of 'loos::LOOSError'
  what():  Internal overflow compressing coordinates
```

**Comment by agrossfield** [comment]
I agree this is reasonable. The challenge will be where to put such checks. Some could go at the top level (eg in the core Trajectory class, check ping for 0 size files, etc), but a lot of our file reading is done in subclasses, and the particular kinds of errors to look for vary wildly. I guess the obvious thing to do is go look at every throw in code that works with files.

**Comment by tromo** [comment]
I think this is really two issues: a very general and limited scope one...  The general one is that all objects that store a filename inside of them (i.e. models and trajectories) should include that name (or just "stream" if they were invoked with a stream instead) in any error message they print or throw.  The more specific one is that msgs describing internal errors should be more descriptive (and include diagnostic suggestions).  They may be good for the developers, but frustrating for the end-user.

**Comment by lgsmith** [comment]
I had thought about it as a 'modifying messages' feature too, but honestly certain types of--to me--inscrutable errors loos can emit basically come from reading or writing zero frame trajs, so having a check for that could be pretty healthy for the user ecosystem in general. Is that functionality that could be added to the constructor of the Trajectory class?

**Comment by agrossfield** [comment]
We can probably add a few simple checks to the Trajectory class, but they won't work for everything. The challenge will be that some of the error messages don't come from code we wrote, but either from libraries (netcdf, hdf5, gemmi) or code we imported whole (e.g. the xtc readers and writers, as in your example). In those cases, what would be required is catching the errors those various libraries throw and replacing/supplementing the error messages with some additional more informative stuff.

**Comment by lgsmith** [comment]
I think catching the error and then simply appending a string with some extra information--particularly the filename--would be a great start. I imagine I'd want that for _any_ error a trajectory object might possibly throw. Seems like most of the errors are of type LOOSError, so maybe catching any loos error and appending a string with the file name would work?

**Comment by agrossfield** [comment]
@AksharaSharma98 is working on this

**Comment by lgsmith** [comment]
W00t! Thanks for this folks!
