### ISSUE TITLE
Quick question : windows subsystem? 

### ISSUE THREAD

**Issue by krb0073** [GrossfieldLab/loos#12]
Hello Grossfield lab, 
I was wondering if LOOS would be okay to be complied using the Windows Linux system? 
I was hoping to still have my home computer in windows while using a Debian subsystem  windows to run a couple programs I use for work.

Kyle

**Comment by agrossfield** [comment]
I honestly don’t know. My guess is that if you follow the instructions for installing under Debian, it’ll work, but I’ve never tried.

If you try and it works, let me know so I can update the docs. If you try and it doesn’t work, let me know and I’ll try to help you get it working.

**Comment by krb0073** [comment]
Following  the instructions for installing under Debian I am able to get LOOS to install on the subsystem, and I have only one issue so far. when trying to call OMG by itself I get.

{
ImportError: /usr/local/src/loos/_loos.so: undefined symbol: PyCObject_Type
}

Also I was able to use the make_libray.inp to make a lipid libary and tried using OMG to make a system. I ran into a issues where the OMG would finish but the psf and pdb do not have the same number atoms in them. I makes both though. I think this is an error on my end not yours;
Kyle

**Comment by agrossfield** [comment]
Hi Kyle,

It sounds like LOOS is running for you, so I'll focus on the last piece, the apparent mismatch in the number of atoms.  The key question is which pdb and psf are you comparing? The final resulting pdb is hardwired to be named final.pdb, while the psf name is chosen by the user with the "psf" option.  It does write out other structures along the way -- perhaps you're comparing a different one?

If I misread your note and you can't import LOOS under debian, there are 2 things to try.  The first is a very simple test: just run python3 from the command line and say 

`import loos
`
You should get the same error you reported getting above.  

If so, I have a couple of guesses:

1. Did you source setup.sh before trying to run? It's necessary to get the environment set up right.
2. If that wasn't it, it's possible you'll need to change the value of PYTHON_INC in custom.py. You should be able to figure out the right directory name by saying 

`ls -d /usr/include/python*
`
You'll see 2 directories, "/usr/include/python2.7/" and something that contains python3.  Choose the latter, put it into custom.py (if you haven't already done it, you'll need to create it by copying custom.py-proto -- PYTHON_INC is at the bottom of the file), then do a clean rebuild:

```
scons -c
scons -c config
scons 
```

Hope this helps,

Alan
