### ISSUE TITLE
PyLoos:  import loos won't release the GIL

### ISSUE THREAD

**Issue by dejunlin** [GrossfieldLab/loos#27]
**Describe the bug**
`import loos` will prevent other python modules from multithreading

**To Reproduce**
```python
import numpy as np
import math
**import loos 
import loos.pyloos**
import scipy as sp
from numba import njit, prange

@njit(parallel=True, fastmath=True)
def invsqrt(n : int):
	a = np.random.randn(n)
	for i in prange(a.shape[0]):
		a[i] = 1.0 / math.sqrt(math.fabs(a[i]))
	return a

ai = invsqrt(3000000000)
print(ai[-1])
```

Profiling shows this program only uses 1 cpu thread on numba OpenMP backend

**Expected behavior**
As what happens with the loss and pyloss import lines commented out, the program uses multiple threads to compute the `invsqrt()`

**LOOS version and platform
master head on CentOS 6.9

**Additional context**
This is most likely due to SWIG. According to http://www.swig.org/Doc4.0/Python.html, swig-compiled loos won't release the GIL unless "-threads" option is used so this patches solves the problem for me but I am not sure if it will be generally applicable.
```
diff --git a/SConstruct b/SConstruct
index 6983df11..1d6df2ac 100644
--- a/SConstruct
+++ b/SConstruct
@@ -84,7 +84,7 @@ if "CONDA_PREFIX" in os.environ:
     env = Environment(ENV=os.environ,
                       options=opts,
                       toolpath='.',
-                      SWIGFLAGS=['-c++', '-python', '-Wall', '-py3'],
+                      SWIGFLAGS=['-c++', '-python', '-threads', '-Wall', '-py3'],
                       SHLIBPREFIX=""
                   )
     env["CONDA_PREFIX"]=os.environ["CONDA_PREFIX"]
@@ -93,7 +93,7 @@ else:
     env = Environment(ENV={'PATH': os.environ['PATH']},
                       options=opts,
                       toolpath='.',
-                      SWIGFLAGS=['-c++', '-python', '-Wall', '-py3'],
+                      SWIGFLAGS=['-c++', '-python', '-threads', '-Wall', '-py3'],
                       SHLIBPREFIX=""
                       )
     env.USING_CONDA = False
```
@tromo @agrossfield

**Comment by agrossfield** [comment]
This looks very reasonable, and from what I can tell will just be a no-op if the version of swig doesn't support it.

**Comment by agrossfield** [comment]
Fixed by [commit](https://github.com/GrossfieldLab/loos/commit/16296e2f4103a592b473d6a24c13b5cb7b777ef3l)
