### ISSUE TITLE
Erroneous results from threaded tools with Fedora and openblas

### ISSUE THREAD

**Issue by tromo** [GrossfieldLab/loos#6]
It seems that there's an issue when using recent Fedoras and openblas with multithreaded LOOS tools, such as multi-rmsds, rmsds, rms-overlap, and trans-rmsds.  You may get incorrect (e.g. very large) results.  Our testing indicates that linking with openblasp rather than openblas will solve the problem.  Note: you may want/need to set openblas to use only one CPU and let LOOS do the threading in this case.

**Comment by agrossfield** [comment]
Just to be clear: this is Fedora 28, not all Fedoras

**Comment by tromo** [comment]
To build with openblasp, the simplest method is to rename the included custom.py-proto to custom.py, then edit the very end of the file.  You will see a commented line that says "Uncomment the following to use the threaded version of OpenBLAS".  Uncomment that line (and comment any other ATLAS_LIBS line you may have been using) and you should be fine.
