### ISSUE TITLE
Compiling issue with scons

### ISSUE THREAD

**Issue by Alan-Rusty24** [GrossfieldLab/loos#7]
OS : Ubuntu 18.04
Libraries installed: boost, netcdf, blas, lapack, atlas
Motivation : I came across your wham analysis code and saw that you have also written a handful of libraries to do a lot of important analysis for trajectory files and was just curious to try it out. However, failed at compiling the libraries. After resolving errors corresponding to scons, not finding numpy(because it was looking for python 2.7 specifically), etc. I failed and got stuck at the error as follows.

I've created a python environment to install python2.7 and corresponding numpy, scipy, and scons and have that environment activated while attempting to build. Also custom.py file was created to provide correct path to atlas, boost, netcdf libraries and the corresponding python_path. Attaching both custom.py and error.log file where I'm dumping the terminal output I receive while compiling. Following command was used to build
scons PREFIX=$HOME/Softwares/loos/build install

[custom.py.txt](https://github.com/GrossfieldLab/loos/files/2471132/custom.py.txt)
[error.log.txt](https://github.com/GrossfieldLab/loos/files/2471133/error.log.txt)

It looks like a Timer issue but I could not figure it out myself. 

To cut things short, the exact couple of lines as it fails were:
In file included from src/utils.hpp:50:0,
                 from src/loos.hpp:54,
                 from Tools/aligner.cpp:35:
src/Coord.hpp:129:41: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     T& operator[](const unsigned int i) throw(std::out_of_range) {
                                         ^~~~~
src/Coord.hpp:136:53: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     const T& operator[](const unsigned int i) const throw(std::out_of_range) {
                                                     ^~~~~
src/Coord.hpp:165:68: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
     friend std::istream& operator>>(std::istream& is, Coord<T>& i) throw(std::runtime_error){
                                                                    ^~~~~
In file included from src/loos.hpp:75:0,
                 from Tools/aligner.cpp:35:
src/Trajectory.hpp:73:36: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   Trajectory(const std::string& s) throw(FileOpenError)
                                    ^~~~~
In file included from src/loos.hpp:75:0,
                 from Tools/aligner.cpp:35:
src/Trajectory.hpp:280:49: warning: dynamic exception specifications are deprecated in C++11 [-Wdeprecated]
   void setInputStream(const std::string& fname) throw(FileOpenError)
                                                 ^~~~~
In file included from src/ensembles.hpp:34:0,
                 from src/loos.hpp:101,
                 from Tools/aligner.cpp:35:
src/ProgressCounters.hpp:104:5: error: ‘Timer’ does not name a type; did you mean ‘time’?
     Timer<WallTimer> timer_;
     ^~~~~
     time

**Comment by agrossfield** [comment]
Are you using conda to make the environment? If so, it ought to compile correctly with no customization at all.

**Comment by agrossfield** [comment]
I’m sorry — I should have also said we’ll look at your stuff more carefully tomorrow.

**Comment by Alan-Rusty24** [comment]
No problem. I was just curious to try out loos for learning purpose and see if could be useful for me but it took significant amount of time just to start it to compile and then i couldn't resolve the timer error. In any case, it's not very urgent for me now to have to make it work. It was just out of curiosity.

**Comment by tromo** [comment]
There are a couple of possibilities.  The first is that scons caches some of its results and that can sometimes cause it to get confused.  Try clearing out everything and running again with,
```scons -c ; scons -c config ; scons```

The other possibility is that there's a collision in header file name.  Timer comes from src/timer.hpp, which is an unfortunately generic name.  You could try searching for other instances of timer.hpp and see if any are in the include path scons is using.

You really shouldn't be having these problems though.  I use a conda3 with python-2.7 env to build on my mac.  However, we haven't tested that setup in debian, only installing dependencies via apt-get.

**Comment by Alan-Rusty24** [comment]
There is a timer.hpp from boost libraries and maybe that's where the issue is arising from. I already cleaning cache with scons -c. It didn't work.

**Comment by tromo** [comment]
Just to be clear, "scons -c" only clears out the build files but doesn't actually clear the autoconfig cache.  You have to follow it with "scons -c config" (that's our hack to clean out everything).

Regardless, I think timer.hpp is too generic, and correcting the include path order in scons can be a pain, so I've renamed timer.hpp to loos_timer.hpp and pushed that update to github.  Please pull the latest version and try building with it.  If this doesn't solve the problem, then let us know.

**Comment by Alan-Rusty24** [comment]
1. It worked with the timer update. It indeed was clashing with generic timer.hpp from boos libraries
2. It failed to compile due to dxoygen not installed.
3. It worked after installing doxygen and successfully compilled.

**Comment by Alan-Rusty24** [comment]
Sure. I'll compile the list of things and get back to you soon. I'll also try it on a different virtual-box and can have all the commands (i used for libraries installation) in a file so it's much easier to reproduce the errors, if any!

**Comment by agrossfield** [comment]
Thanks — we appreciate it!

Alan


> On Oct 19, 2018, at 3:05 PM, Alankar Rastogi <notifications@github.com> wrote:
> 
> Sure. I'll compile the list of things and get back to you soon. I'll also try it on a different virtual-box and can have all the commands (i used for libraries installation) in a file so it's much easier to reproduce the errors, if any!
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_GrossfieldLab_loos_issues_7-23issuecomment-2D431466486&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=EhShoCQtKJ_s7s9ZR0yJXz6SPbEULMPkQi9jbqQ7O4E&s=JEPSOgznrLl_L7iryFApjiCwhnBqd1V1wieUf6wI52E&e=>, or mute the thread <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AM-5F-2D8kTy45q05vVN0rA3cCxhiacu5bK3ks5umiKEgaJpZM4XYlpa&d=DwMCaQ&c=4sF48jRmVAe_CH-k9mXYXEGfSnM3bY53YSKuLUQRxhA&r=49qnaP-kgQR_zujl5kbj_PmvQeXyz1NAoiLoIzsc27zuRX32UDM2oX8NQCaAsZzH&m=EhShoCQtKJ_s7s9ZR0yJXz6SPbEULMPkQi9jbqQ7O4E&s=hGXTIprCeb08rz3aqVCAVKNkP3akywUo0Mn5DhNZfw0&e=>.
> 

________________________________
Dr. Alan Grossfield
Associate Professor
Department of Biochemistry and Biophysics
University of Rochester Medical Center
610 Elmwood Ave, Box 712
Rochester, NY 14642
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789

**Comment by Alan-Rusty24** [comment]
I apologize for the delay!
Please find the file attached which has all the instructions I typed on the terminal to install any libraries and what environment I had activated while installation. Also, my custom.py file to specify the path to the libraries and include files.
[What_was_Done.txt](https://github.com/GrossfieldLab/loos/files/2502563/What_was_Done.txt)
[custom.py.txt](https://github.com/GrossfieldLab/loos/files/2502584/custom.py.txt)
Please let me know if you need anything else!

**Comment by agrossfield** [comment]
Thanks -- we'll update the docs!
