### ISSUE TITLE
Add documentation of uninstall and removal of binaries/compilation configs for cmake build

### ISSUE THREAD

**Issue by lgsmith** [GrossfieldLab/loos#87]
**Is your feature request related to a problem? Please describe.**
Problem: I don't know how to totally clean up loos's cmake build.

**Describe the solution you'd like**
The equilvalent of running `scons -c; scons -c config` should be provided in the install docs in uninstall. Even if it's just `rm -rf path/to/loos/build`

**Describe alternatives you've considered**
This seems to be the only sensible alternative, and I'm sure it's known. It just needs to be documented.

**Comment by lgsmith** [comment]
There should maybe be a special entry on how to upgrade a directory that might have a previous scons build sitting in it. I think that's causing me problems upgrading from a recent 3.x main build to 4.0.

**Comment by agrossfield** [comment]
There is a "clean" target for cmake. From the build directory, you can say 
```
cmake --build . --target clean
```

Removing the build tree will also work, but I think you lose the dependency tree that way, so the next rebuild will be slower.

**Comment by lgsmith** [comment]
I know this is closed; I wanted to add for posterity that if you have a conda env with other compiled tools built into it from other libs (i.e. a conda env that would be annoying to rebuild) you can try to use `scons -c; scons -c config` *prior to upgrading*. I didn't think about it until after upgrading, so I had to check out 3.3 and then do it, but it seemed to work.

**Comment by agrossfield** [comment]
I know – I put exactly that comment into INSTALL.md. I agree having it here as well can only be helpful.

________________________________
Dr. Alan Grossfield
Dept of Biochemistry and Biophysics
University of Rochester Medical Center
Phone: 585 276 4193
http://membrane.urmc.rochester.edu
https://orcid.org/0000-0002-5877-2789
Pronouns: He/his



From: lgsmith ***@***.***>
Reply-To: GrossfieldLab/loos ***@***.***>
Date: Tuesday, October 25, 2022 at 4:23 PM
To: GrossfieldLab/loos ***@***.***>
Cc: "Grossfield, Alan" ***@***.***>, State change ***@***.***>
Subject: [EXT] Re: [GrossfieldLab/loos] Add documentation of uninstall and removal of binaries/compilation configs for cmake build (Issue #87)


I know this is closed; I wanted to add for posterity that if you have a conda env with other compiled tools built into it from other libs (i.e. a conda env that would be annoying to rebuild) you can try to use scons -c; scons -c config prior to upgrading. I didn't think about it until after upgrading, so I had to check out 3.3 and then do it, but it seemed to work.
