### ISSUE TITLE
Conda-forge package 4.0.2 doesn't have netcdf support

### ISSUE THREAD

**Issue by agrossfield** [GrossfieldLab/loos#91]
**Describe the bug**
The version of loos you get from conda-forge doesn't support netcdf.

**To Reproduce**
Run any binary that supports trajectories, eg `trajinfo`. Netcdf format isn't listed among the supported formats. If you try to feed a tool a netcdf, it says it's not a supported format

**Expected behavior**
LOOS supports netcdf, so something went wrong with the conda-forge build.

**LOOS version and platform
loos 4.0.2 from conda-forge on linux

**Comment by agrossfield** [comment]
Just checked -- same problem in the package on Mac:
```
(loos-test) jordan 3% trajinfo
Usage- trajinfo [options] model trajectory 
Allowed Options:
  --config arg                Options config file
  --fullhelp                  More detailed help
  -h [ --help ]               Produce this message
  -v [ --verbosity ] arg (=0) Verbosity of output (if available)
  -k [ --skip ] arg (=0)      Number of frames to skip
  --modeltype arg             Model types:
                              prmtop = Amber
                              crd = CHARMM CRD
                              pdb = CHARMM/NAMD PDB
                              psf = CHARMM/NAMD PSF
                              gro = Gromacs
                              xyz = Tinker
                              
  --trajtype arg              Trajectory types:
                              crd = Amber Traj
                              mdcrd = Amber Traj
                              inpcrd = Amber Restart
                              rst = Amber Restart
                              rst7 = Amber Restart
                              dcd = CHARMM/NAMD DCD
                              pdb = Concatenated PDB
                              trr = Gromacs TRR
                              xtc = Gromacs XTC
                              arc = Tinker ARC
                              
  -B [ --brief ] arg (=0)     Minimal output
  --centroid arg              Report average centroid of selection
  --box arg (=0)              Report periodic box info
  --verify arg (=1)           Verify frame count
```

Weirdly, on linux I used ldd and I can see that the binary is linked against libnetcdf. `otool -L` on Mac does not list libnetcdf.

**Comment by agrossfield** [comment]
For now, the workaround if you need netcdf support (eg because you use amber or the netcdf trajectory format with openmm) you'll need to build loos from GitHub. 

We hope to have this fixed in a few days.

**Comment by agrossfield** [comment]
Ugh -- it's worse than that. It's gone from the main branch as well.  What's weird is I can see the build *FOUND* the library, and it compiled amber_netcdf.cpp. It's as if it didn't set the switch to tell the programs it's there though. 

Summoning @tromo for help.

**Comment by tromo** [comment]
I think I see the problem, but it's going to take a little investigation to make sure all instances like that are fixed.  I'll also role the Xcode issue into this one and [hopefully] tackle both with 4.0.3
